Budget App Milestone
Nejjari001/budget-app pull request #5
Opened 2023-03-16 15:44 UTC by Nejjari001

##  In this solo ruby on rails capstone, I implemented the following requirements

- [ ] Splash screen
- A simple page with the name of your app (yes, you need to choose one), and links to the signup and log-in pages.

- [ ] Sign-up and login pages
- The user should be able to register in the app with full name, email, and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- [ ] Home page (categories page)
- When the user logs in, they are presented with the categories page.
- For each category, the user can see their name, icon, and the total amount of all the transactions that belong to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button "add a new category" at the bottom that brings the user to the page to create a new category

- [ ] Transactions page
- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user can see the total amount for the category (the sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ] "Add a new category" page
-  The user fills out a form to create a new category, indicating their name and icon (both mandatory).
- The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ] "Add a new transaction" page
- The user fills out a form to create a new transaction with the following:
name (mandatory), amount (mandatory), categories (mandatory at least one)
- The user clicks (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
- When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

- [ ] Testing requirements
- Create unit and integration tests for all the essential components of your RoR application.

2023-03-17 16:12 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Nejjari001👋, 

### You are doing a marvelous job on the RoR capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://user-images.githubusercontent.com/83803414/225942647-93362227-e108-4696-b8a9-f9904d82d9d8.png)

## To Highlight 🎉
- All tests are passed. ✔️
- Highly organized code. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- Nice UI design. ✔️
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Please make sure to record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes as requested in the project requirements. Add the link to the presentation video in the PR and in the README file. The content of the video should include:
  - Description of the project.
  - Demo of the project features.
  - You should also highlight some interesting piece of code.

- [ ] Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 16:12 UTC, thecodechaser commented on app/views/groups/index.html.erb
> +</div>
- [ ] Please make sure the user can see the total amount of all the transactions that belong to that category on the category(home) page as requested in the project requirements. Currently, The name and icon are visible but not the total amount of all the transactions.

![image](https://user-images.githubusercontent.com/83803414/225943001-33153da4-363f-423d-8947-126499a1b879.png)

2023-03-17 16:12 UTC, thecodechaser commented on app/views/entities/new.html.erb
> +</div>
- [ ] Please make sure when the user clicks the "Save" button to create the new transaction user is redirected to the transactions page for that category as requested in the project requirements. Currently, the User is redirecting to the category(home) page.

![image](https://user-images.githubusercontent.com/83803414/225944548-4cf079ab-be97-4a4a-b6f3-42db03d7eaf3.png)

2023-03-17 16:12 UTC, thecodechaser commented on app/views/entities/new.html.erb
> +</div>
- [ ] Please make sure when the user clicks on the "Back" button on the Add a new transaction page the user is redirected to the transactions page for that category as requested in the project requirements. Currently, the User is redirecting to the category(home) page.

![image](https://user-images.githubusercontent.com/83803414/225945354-aec90ef6-1c43-4c12-98bf-e7d30537ce30.png)

2023-03-17 16:12 UTC, thecodechaser commented on README.md
> +
- [ ] The live demo link in the README is not working, There are some errors please fix them and make sure the project is deployed and accessible online and the live demo link in the README works as expected as requested in the project requirements.

![image](https://user-images.githubusercontent.com/83803414/225948340-23a01770-18df-45d7-b252-ec355bf76a03.png)

2023-03-18 16:16 UTC, Whoistolu commented on app/views/groups/index.html.erb
> +</div>
- Well resolved 👍🏽

2023-03-18 16:16 UTC, Whoistolu commented on app/views/entities/new.html.erb
> +</div>
- Well resolved 👍🏽

2023-03-18 16:17 UTC, Whoistolu commented on app/views/entities/new.html.erb
> +</div>
- Well resolved 👍🏽

2023-03-18 16:17 UTC, Whoistolu commented on README.md
> +
- Well resolved 👍🏽

2023-03-18 16:23 UTC, Whoistolu approved these changes
### Hi @Nejjari001 

Great job implementing all the recommendations by the previous reviewer 👍🏽 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-18 16:24 UTC, merged